<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BranchController;
use App\Http\Controllers\Api\CompanySettingController;
use App\Http\Controllers\Api\EquipmentController;
use App\Http\Controllers\Api\EquipmentPartController;
use App\Http\Controllers\Api\LineController;
use App\Http\Controllers\Api\LocationController;
use App\Http\Controllers\Api\MachineController;
use App\Http\Controllers\Api\PartController;
use App\Http\Controllers\Api\PartInstallationController;
use App\Http\Controllers\Api\PartRepairController;
use App\Http\Controllers\Api\PartStockController;
use App\Http\Controllers\Api\PartReplacementRequestController;
use App\Http\Controllers\Api\PartSupplierController;
use App\Http\Controllers\Api\PartUnitActionRequestController;
use App\Http\Controllers\Api\PartUnitController;
use App\Http\Controllers\Api\PublicBreakdownController;
use App\Http\Controllers\Api\PublicPartUnitController;
use App\Http\Controllers\Api\ReorderRequestController;
use App\Http\Controllers\Api\StockAlertController;
use App\Http\Controllers\Api\SupplierController;
use App\Http\Controllers\Api\TaskController;
use App\Http\Controllers\Api\TaskLibraryController;
use App\Http\Controllers\Api\TaskLibraryPartController;
use App\Http\Controllers\Api\UnitController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\WorkOrderController;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:login');

// Unauthenticated shop-floor QR-scan flows: read-only lookups plus submitting
// a request. Nothing here touches stock or installations — that only happens
// once an Engineer/Teknisi approves the request (see below).
Route::middleware('throttle:breakdown-public')->prefix('public')->group(function () {
    Route::get('/parts/{part}', [PublicBreakdownController::class, 'showPart']);
    Route::get('/branches', [PublicBreakdownController::class, 'branches']);
    Route::get('/branches/{branch}/lines', [PublicBreakdownController::class, 'lines']);
    Route::get('/lines/{line}/machines', [PublicBreakdownController::class, 'machines']);
    Route::get('/machines/{machine}/equipment', [PublicBreakdownController::class, 'equipment']);
    Route::get('/parts/{part}/branches/{branch}/equipment', [PublicBreakdownController::class, 'equipmentForPartInBranch']);
    Route::post('/replacement-requests', [PublicBreakdownController::class, 'store']);

    // QR-per-unit flow: scanning the tag on a specific physical part unit —
    // reuses the branches/equipment-for-part lookups above for the reinstall
    // picker, since a unit's part_id feeds the same BOM-filtered endpoint.
    Route::get('/part-units/{partUnit}', [PublicPartUnitController::class, 'show']);
    Route::post('/part-units/{partUnit}/action-requests', [PublicPartUnitController::class, 'store']);
});

Route::middleware('auth:sanctum')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/user', [AuthController::class, 'me']);

    // Master data: any authenticated role can read.
    Route::apiResource('branches', BranchController::class)->only(['index', 'show']);
    Route::apiResource('parts', PartController::class)->only(['index', 'show']);
    Route::get('/units', [UnitController::class, 'index']);
    Route::get('/settings/company', [CompanySettingController::class, 'show']);
    Route::get('/branches/{branch}/suppliers', [SupplierController::class, 'index']);
    Route::get('/suppliers/{supplier}', [SupplierController::class, 'show']);
    Route::get('/branches/{branch}/locations', [LocationController::class, 'index']);
    Route::get('/locations/{location}', [LocationController::class, 'show']);

    // Stock: any authenticated role can view current stock and its history.
    Route::get('/branches/{branch}/part-stocks', [PartStockController::class, 'index']);
    Route::get('/part-stocks/{partStock}', [PartStockController::class, 'show']);
    Route::get('/part-stocks/{partStock}/ledger', [PartStockController::class, 'ledger']);

    // Stock alerts and reorder requests: auto-generated by StockAlertService,
    // any authenticated role can view them.
    Route::get('/branches/{branch}/stock-alerts', [StockAlertController::class, 'index']);
    Route::get('/branches/{branch}/reorder-requests', [ReorderRequestController::class, 'index']);

    // Line > Machine > Equipment hierarchy: any authenticated role can read.
    Route::get('/branches/{branch}/lines', [LineController::class, 'index']);
    Route::get('/lines/{line}', [LineController::class, 'show']);
    Route::get('/lines/{line}/machines', [MachineController::class, 'index']);
    Route::get('/machines/{machine}', [MachineController::class, 'show']);
    Route::get('/machines/{machine}/equipment', [EquipmentController::class, 'index']);
    Route::get('/equipment/{equipment}', [EquipmentController::class, 'show']);

    // Work orders (maintenance schedule templates) and tasks (actual work items):
    // any authenticated role can read.
    Route::get('/equipment/{equipment}/work-orders', [WorkOrderController::class, 'index']);
    Route::get('/branches/{branch}/work-orders', [WorkOrderController::class, 'indexForBranch']);
    Route::get('/work-orders/{workOrder}', [WorkOrderController::class, 'show']);
    Route::get('/parts/{part}/work-orders', [WorkOrderController::class, 'forPart']);
    Route::get('/equipment/{equipment}/tasks', [TaskController::class, 'index']);
    Route::get('/tasks/mine', [TaskController::class, 'mine']);
    Route::get('/tasks/{task}', [TaskController::class, 'show']);

    // Task Library ("PM task" recipes: activity + equipment + planned parts)
    // and the PM schedule/ledger of tasks generated from them: any
    // authenticated role can read.
    Route::get('/equipment/{equipment}/task-libraries', [TaskLibraryController::class, 'index']);
    Route::get('/branches/{branch}/task-libraries', [TaskLibraryController::class, 'indexForBranch']);
    Route::get('/task-libraries/{taskLibrary}', [TaskLibraryController::class, 'show']);
    Route::get('/branches/{branch}/pm-tasks', [TaskController::class, 'pmSchedule']);
    Route::get('/branches/{branch}/part-lifetime-alerts', [PartInstallationController::class, 'atRisk']);

    // Part <-> Supplier (approved supplier list per part) and Part <-> Equipment
    // (BOM) relations, plus part lifetime tracking: any authenticated role can read.
    Route::get('/parts/{part}/suppliers', [PartSupplierController::class, 'index']);
    Route::get('/suppliers/{supplier}/parts', [PartSupplierController::class, 'forSupplier']);
    Route::get('/equipment/{equipment}/parts', [EquipmentPartController::class, 'index']);
    Route::get('/parts/{part}/equipment', [EquipmentPartController::class, 'forPart']);
    Route::get('/equipment/{equipment}/part-installations', [PartInstallationController::class, 'index']);
    Route::get('/parts/{part}/part-installations', [PartInstallationController::class, 'forPart']);
    Route::get('/locations/{location}/part-stocks', [PartStockController::class, 'forLocation']);

    // Part units: one row per physical, trackable part instance — its
    // install/repair history across equipment and repair cycles.
    Route::get('/parts/{part}/units', [PartUnitController::class, 'index']);
    Route::get('/part-units/{partUnit}', [PartUnitController::class, 'show']);
    Route::get('/part-repairs', [PartRepairController::class, 'index']);

    // Any authenticated role can work their own tasks and log line runtime.
    Route::post('/tasks/{task}/start', [TaskController::class, 'start']);
    Route::post('/tasks/{task}/complete', [TaskController::class, 'complete']);
    Route::post('/tasks/{task}/cancel', [TaskController::class, 'cancel']);
    Route::post('/lines/{line}/runtime', [LineController::class, 'addRuntime']);

    // Master data: only warehouse admin, supervisor, and superadmin can write.
    Route::middleware('role:admin_gudang|supervisor|superadmin')->group(function () {
        Route::apiResource('branches', BranchController::class)->only(['store', 'update', 'destroy']);
        Route::apiResource('parts', PartController::class)->only(['store', 'update', 'destroy']);
        Route::post('/units', [UnitController::class, 'store']);
        Route::put('/units/{unit}', [UnitController::class, 'update']);
        Route::delete('/units/{unit}', [UnitController::class, 'destroy']);
        Route::put('/settings/company', [CompanySettingController::class, 'update']);
        Route::post('/branches/{branch}/suppliers', [SupplierController::class, 'store']);
        Route::put('/suppliers/{supplier}', [SupplierController::class, 'update']);
        Route::delete('/suppliers/{supplier}', [SupplierController::class, 'destroy']);
        Route::post('/branches/{branch}/locations', [LocationController::class, 'store']);
        Route::put('/locations/{location}', [LocationController::class, 'update']);
        Route::delete('/locations/{location}', [LocationController::class, 'destroy']);

        Route::post('/part-stocks/{partStock}/receive', [PartStockController::class, 'receive']);
        Route::post('/part-stocks/{partStock}/adjust', [PartStockController::class, 'adjust'])
            ->middleware('throttle:stock-adjustment');
        Route::put('/part-stocks/{partStock}/location', [PartStockController::class, 'updateLocation']);

        Route::post('/branches/{branch}/lines', [LineController::class, 'store']);
        Route::put('/lines/{line}', [LineController::class, 'update']);
        Route::delete('/lines/{line}', [LineController::class, 'destroy']);
        Route::post('/lines/{line}/machines', [MachineController::class, 'store']);
        Route::put('/machines/{machine}', [MachineController::class, 'update']);
        Route::delete('/machines/{machine}', [MachineController::class, 'destroy']);
        Route::post('/machines/{machine}/equipment', [EquipmentController::class, 'store']);
        Route::put('/equipment/{equipment}', [EquipmentController::class, 'update']);
        Route::delete('/equipment/{equipment}', [EquipmentController::class, 'destroy']);

        Route::post('/equipment/{equipment}/work-orders', [WorkOrderController::class, 'store']);
        Route::put('/work-orders/{workOrder}', [WorkOrderController::class, 'update']);
        Route::delete('/work-orders/{workOrder}', [WorkOrderController::class, 'destroy']);
        Route::post('/work-orders/{workOrder}/generate-task', [WorkOrderController::class, 'generateTask']);

        Route::post('/equipment/{equipment}/tasks', [TaskController::class, 'store']);
        Route::put('/tasks/{task}', [TaskController::class, 'update']);
        Route::delete('/tasks/{task}', [TaskController::class, 'destroy']);

        Route::post('/equipment/{equipment}/task-libraries', [TaskLibraryController::class, 'store']);
        Route::put('/task-libraries/{taskLibrary}', [TaskLibraryController::class, 'update']);
        Route::delete('/task-libraries/{taskLibrary}', [TaskLibraryController::class, 'destroy']);
        Route::post('/task-libraries/{taskLibrary}/parts', [TaskLibraryPartController::class, 'store']);
        Route::delete('/task-library-parts/{taskLibraryPart}', [TaskLibraryPartController::class, 'destroy']);
        Route::post('/task-libraries/{taskLibrary}/schedule', [TaskLibraryController::class, 'schedule']);

        Route::get('/users', [UserController::class, 'index']);

        Route::post('/reorder-requests/{reorderRequest}/approve', [ReorderRequestController::class, 'approve']);
        Route::post('/reorder-requests/{reorderRequest}/mark-ordered', [ReorderRequestController::class, 'markOrdered']);
        Route::post('/reorder-requests/{reorderRequest}/cancel', [ReorderRequestController::class, 'cancel']);

        Route::post('/parts/{part}/suppliers', [PartSupplierController::class, 'store']);
        Route::put('/part-suppliers/{partSupplier}', [PartSupplierController::class, 'update']);
        Route::delete('/part-suppliers/{partSupplier}', [PartSupplierController::class, 'destroy']);

        Route::post('/equipment/{equipment}/parts', [EquipmentPartController::class, 'store']);
        Route::delete('/equipment-parts/{equipmentPart}', [EquipmentPartController::class, 'destroy']);

        Route::post('/equipment/{equipment}/part-installations', [PartInstallationController::class, 'store']);
        Route::post('/part-installations/{partInstallation}/remove', [PartInstallationController::class, 'remove']);
        Route::post(
            '/part-installations/{partInstallation}/schedule-replacement',
            [PartInstallationController::class, 'scheduleReplacement']
        );

        Route::post('/part-units/{partUnit}/repairs', [PartRepairController::class, 'store']);
        Route::put('/part-repairs/{partRepair}', [PartRepairController::class, 'update']);
    });

    // Breakdown replacement approval board: Engineer/Teknisi decide whether a
    // QR-scanned replacement request goes through; supervisor/superadmin get
    // the same oversight access they have everywhere else in the app.
    Route::middleware('role:teknisi|engineer|supervisor|superadmin')->group(function () {
        Route::get('/branches/{branch}/replacement-requests', [PartReplacementRequestController::class, 'index']);
        Route::post('/replacement-requests/{partReplacementRequest}/approve', [PartReplacementRequestController::class, 'approve']);
        Route::post('/replacement-requests/{partReplacementRequest}/reject', [PartReplacementRequestController::class, 'reject']);

        Route::get('/branches/{branch}/part-unit-action-requests', [PartUnitActionRequestController::class, 'index']);
        Route::post('/part-unit-action-requests/{partUnitActionRequest}/approve', [PartUnitActionRequestController::class, 'approve']);
        Route::post('/part-unit-action-requests/{partUnitActionRequest}/reject', [PartUnitActionRequestController::class, 'reject']);
    });
});
