<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BranchController;
use App\Http\Controllers\Api\EquipmentController;
use App\Http\Controllers\Api\LineController;
use App\Http\Controllers\Api\LocationController;
use App\Http\Controllers\Api\MachineController;
use App\Http\Controllers\Api\PartController;
use App\Http\Controllers\Api\PartStockController;
use App\Http\Controllers\Api\ReorderRequestController;
use App\Http\Controllers\Api\StockAlertController;
use App\Http\Controllers\Api\SupplierController;
use App\Http\Controllers\Api\TaskController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\WorkOrderController;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:login');

Route::middleware('auth:sanctum')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/user', [AuthController::class, 'me']);

    // Master data: any authenticated role can read.
    Route::apiResource('branches', BranchController::class)->only(['index', 'show']);
    Route::apiResource('parts', PartController::class)->only(['index', 'show']);
    Route::get('/branches/{branch}/suppliers', [SupplierController::class, 'index']);
    Route::get('/suppliers/{supplier}', [SupplierController::class, 'show']);
    Route::get('/branches/{branch}/locations', [LocationController::class, 'index']);
    Route::get('/locations/{location}', [LocationController::class, 'show']);

    // Stock: any authenticated role can view current stock and its history.
    Route::get('/branches/{branch}/part-stocks', [PartStockController::class, 'index']);
    Route::get('/part-stocks/{partStock}', [PartStockController::class, 'show']);
    Route::get('/part-stocks/{partStock}/ledger', [PartStockController::class, 'ledger']);

    // Stock alerts and reorder requests: auto-generated by StockAlertService,
    // any authenticated role can view them.
    Route::get('/branches/{branch}/stock-alerts', [StockAlertController::class, 'index']);
    Route::get('/branches/{branch}/reorder-requests', [ReorderRequestController::class, 'index']);

    // Line > Machine > Equipment hierarchy: any authenticated role can read.
    Route::get('/branches/{branch}/lines', [LineController::class, 'index']);
    Route::get('/lines/{line}', [LineController::class, 'show']);
    Route::get('/lines/{line}/machines', [MachineController::class, 'index']);
    Route::get('/machines/{machine}', [MachineController::class, 'show']);
    Route::get('/machines/{machine}/equipment', [EquipmentController::class, 'index']);
    Route::get('/equipment/{equipment}', [EquipmentController::class, 'show']);

    // Work orders (maintenance schedule templates) and tasks (actual work items):
    // any authenticated role can read.
    Route::get('/equipment/{equipment}/work-orders', [WorkOrderController::class, 'index']);
    Route::get('/work-orders/{workOrder}', [WorkOrderController::class, 'show']);
    Route::get('/equipment/{equipment}/tasks', [TaskController::class, 'index']);
    Route::get('/tasks/mine', [TaskController::class, 'mine']);
    Route::get('/tasks/{task}', [TaskController::class, 'show']);

    // Any authenticated role can work their own tasks and log line runtime.
    Route::post('/tasks/{task}/start', [TaskController::class, 'start']);
    Route::post('/tasks/{task}/complete', [TaskController::class, 'complete']);
    Route::post('/tasks/{task}/cancel', [TaskController::class, 'cancel']);
    Route::post('/lines/{line}/runtime', [LineController::class, 'addRuntime']);

    // Master data: only warehouse admin, supervisor, and superadmin can write.
    Route::middleware('role:admin_gudang|supervisor|superadmin')->group(function () {
        Route::apiResource('branches', BranchController::class)->only(['store', 'update', 'destroy']);
        Route::apiResource('parts', PartController::class)->only(['store', 'update', 'destroy']);
        Route::post('/branches/{branch}/suppliers', [SupplierController::class, 'store']);
        Route::put('/suppliers/{supplier}', [SupplierController::class, 'update']);
        Route::delete('/suppliers/{supplier}', [SupplierController::class, 'destroy']);
        Route::post('/branches/{branch}/locations', [LocationController::class, 'store']);
        Route::put('/locations/{location}', [LocationController::class, 'update']);
        Route::delete('/locations/{location}', [LocationController::class, 'destroy']);

        Route::post('/part-stocks/{partStock}/receive', [PartStockController::class, 'receive']);
        Route::post('/part-stocks/{partStock}/adjust', [PartStockController::class, 'adjust'])
            ->middleware('throttle:stock-adjustment');

        Route::post('/branches/{branch}/lines', [LineController::class, 'store']);
        Route::put('/lines/{line}', [LineController::class, 'update']);
        Route::delete('/lines/{line}', [LineController::class, 'destroy']);
        Route::post('/lines/{line}/machines', [MachineController::class, 'store']);
        Route::put('/machines/{machine}', [MachineController::class, 'update']);
        Route::delete('/machines/{machine}', [MachineController::class, 'destroy']);
        Route::post('/machines/{machine}/equipment', [EquipmentController::class, 'store']);
        Route::put('/equipment/{equipment}', [EquipmentController::class, 'update']);
        Route::delete('/equipment/{equipment}', [EquipmentController::class, 'destroy']);

        Route::post('/equipment/{equipment}/work-orders', [WorkOrderController::class, 'store']);
        Route::put('/work-orders/{workOrder}', [WorkOrderController::class, 'update']);
        Route::delete('/work-orders/{workOrder}', [WorkOrderController::class, 'destroy']);
        Route::post('/work-orders/{workOrder}/generate-task', [WorkOrderController::class, 'generateTask']);

        Route::post('/equipment/{equipment}/tasks', [TaskController::class, 'store']);
        Route::put('/tasks/{task}', [TaskController::class, 'update']);
        Route::delete('/tasks/{task}', [TaskController::class, 'destroy']);

        Route::get('/users', [UserController::class, 'index']);

        Route::post('/reorder-requests/{reorderRequest}/approve', [ReorderRequestController::class, 'approve']);
        Route::post('/reorder-requests/{reorderRequest}/mark-ordered', [ReorderRequestController::class, 'markOrdered']);
        Route::post('/reorder-requests/{reorderRequest}/cancel', [ReorderRequestController::class, 'cancel']);
    });
});
